### ISSUE TITLE
API Not Wokring

### ISSUE THREAD

**Issue by raedinkhaled** [bilobom/covid19API#1]
Hello,

Thank your for your effort, I cloned the repo and started the server but I think the API isn't working.
If you can check it again

**Comment by bilobom** [comment]
I have made changes , @raedinkhaled  can you check ?

**Comment by bilobom** [comment]
I'm gonna close the issue, feel free to open it again if not working

**Comment by raedinkhaled** [comment]
It's working now but, can you add also the General Satistics?
mayber the route could be api/covid19/all
and it returns the Total Confirmer and Actual Confirmed and Healed , and Total deaths
otherwise, good Job.

**Comment by raedinkhaled** [comment]
there is another issue, api/covid19/16 is giving stats about Tizi ouzou and not Algiers,
api/covid19/15 is giving stats about Tiaret
api/covid19/19 is giving stats about Jijel.. etc

**Comment by bilobom** [comment]
I have opened new issues for your questions. thanks @raedinkhaled

**Comment by bilobom** [comment]
I have opened new issues for your questions. thanks @raedinkhaled
