### ISSUE TITLE
can you add also the General Satistics?

### ISSUE THREAD

**Issue by bilobom** [bilobom/covid19API#3]
@raedinkhaled
It's working now but, can you add also the General Satistics?
mayber the route could be api/covid19/all
and it returns the Total Confirmer and Actual Confirmed and Healed , and Total deaths

**Comment by bilobom** [comment]
@raedinkhaled added total cases with recovered, active, dead

**Comment by raedinkhaled** [comment]
Hello again, it's getting wrong numbers: for ex : today total cases were : 1825 but the API Shows 1822
there is also problem with active and recovered Cases.

**Comment by bilobom** [comment]
@raedinkhaled  yes I noticed that. The Government api doesn't return the exact `recovered` number. I left it intentionally as is to strictly reflect the government's data.
What you can do is get all confirmedCases in all provinces via /api/province/all and add them all.

**Comment by raedinkhaled** [comment]
> @raedinkhaled yes I noticed that. The Government api doesn't return the exact `recovered` number. I left it intentionally as is to strictly reflect the government's data.
> What you can do is get all confirmedCases in all provinces via /api/province/all and add them all.

Yes, I thinked of that. but the problem will be with the recovered and active cases because the API doesn't return them corroectly for each Wilaya.
However I found a website that is using the Government's API and bring the right DATA I just don't know how.
anyways, thank you very much for your help.
